name: Build and Test
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        target: [ 'x86_64-unknown-linux-musl', 'x86_64-pc-windows-gnu', 'x86_64-apple-darwin' ]
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
 
    - name: Build
      run: cargo build --target=${{ matrix.target }} --release
 
    - name: Test
      run: cargo test --target=${{ matrix.target }}
